version: '3'

services:
  practical_microservices_db:
    image: postgres:10.3
    environment:
      - POSTGRES_DB=practical_microservices
    ports:
      - '0.0.0.0:5432:5432'
  message-db:
    image: ethangarofolo/message-db:1.1.6
    ports:
      - '0.0.0.0:5433:5432'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

